version: '3'
services:
  web:
    container_name: ndweb
    build:
      context: ../
      dockerfile: dockerfile
      target: dev
    volumes:
      - ../:/usr/src/app
    command: /bin/sh -c "while sleep 1000; do :; done"
    network_mode: service:db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@nddb:5432/postgres?schema=public'
      API_URL: 'http://localhost:3000/api/graphql'
  db:
    container_name: nddb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - nddb:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
volumes:
  nddb: {}
